---
title: Conceptual background
---

## Modelling syntax

Any computational analysis of natural-language syntax must choose a syntactic model suited to its purpose. These pages summarize the goals of `arsgrammatica`, and how its model compares with other models of natural-language syntax.



- [Goals of `arsgrammatica`](./models.qmd)
- Comparison with the [Universal Dependency scheme](./ud.qmd)
- Comparison with the [Agent-Action-Target model](./aat.qmd)


## Implementation of the `arsgrammatica` model


The `arsgrammatica` package is based on three classes, representing the tokenization of a Latin passage, the syntactic anchor points of verbal expressions, and the graph of syntactic relations.

- [Tokenization of a passage](./tokens.qmd) (the `Token` class)
- AAT anchor points: [verbal units](./verbalunits.qmd) (the `VerbalExpression` class)
- [Graph of syntactic relations](./syntactic-analysis.qmd) (the `TokenAnalysis` class)

## Examples of analyses

Four sentences from `arsgrammatica`'s training set illustrate [every recognized syntactic relation](./complete_examples.qmd).