---
title: How `arsgrammatica` tokenizes Latin
---


::: {.callout-note}
In `arsgrammatica` the `Token` class is the primary impementation of these ideas.
:::

## Identifiers

Although `arsgrammatica` can analyze strings of text in Latin, it is primarily intended to analyze passages of Latin with citation references such as CTS URNs. In tokenizing a passage, `arsgrammatica` tracks the citation and ensures that all tokens are uniquely identified within a given citation context.

::: {.callout-note}
## Extending CTS URNs to identify tokens
In practical terms, this means that the token's identifier could be used with a containing URN context to create token-level CTS URNs. If the URN `urn:cts:latinLit:phi0474.phi016.omar:1` identifies passage `1` in Cicero's *Pro Archia*, then we could extend its work component with an exemplar identifier `tokens` and extend the passage component with a token identifier like `t0` to create a new URN `urn:cts:latinLit:phi0474.phi016.omar.tokens:1.t0` to cite the first token in that passage.
:::


## Token categories

Tokenization splits a string into meaningful units that can be analyzed. 
Based on their orthography and content, tokens are classified with one of the following categories that will inform our subsequent analysis.

### `praenomen`

We take an abbreviated praenomen together with its punctuating period as a single token. 

**Example**:  *M. Agrippa L. f. cos. tertium fecit*

The tokens *M.* and *L.* are classified as `praenomen`.

### `abbreviation`

We take other abbreviations, together with their punctuating periods, as single tokens classified as `abbreviation`.

**Example**: *M. Agrippa L. f. cos. tertium fecit* 

Both *f.* and *cos.* are classified as `abbreviation`.


### `punctuation`

Any other Unicode punctuation character, in editions of Latin texts most commonly including period, comma, question mark, semicolon, colon, parentheses and brackets of various kinds, single or double quotation marks, dashes or hyphens, is treated as a distinct token of type `punctuation`

**Example**: *arma virumque cano.*

The period *.* is a token of type `punctuation`.

### `enclitic`

Enclitics belong to a distinct class  because of their orthography, written without space between the enclitic and the preceding token. Tokenization of enclitics must consider the context. 

**Example**: *arma virumque cano.* 

The token *que* is `enclitic`.

**Example**: *ratione docet?*

The string *ratione* represents the enclitic token *ne* (a question word) following the lexical token *ratio* (noun in the nominative singular). 

**Example**: *aequa ratione imperat.*

The string *ratione* is a single lexical token (noun in the ablative singular): there is no enclitic.


Tokenization must also recognize the small number of frequently occurring words that have incorporated an original historic enclitic into a single lexical item such as *quisque* (and its compounds), or *plerusque*. 

**Examples**: forms such as *quisque*, *cuique* and *quemque* must each be treated as a single lexical token.

### `numeral`

Any numeral written numerically rather than phonetically. 

**Example**: *hiberna aberant ab eo milia passuum XXV.* 

`XXV` is a *numeral* token.

**Example**: *fratres Joseph decem venerunt*

All four tokens are *lexical* tokens.


### `lexical`

Lexical tokens written in standard orthography.

**Example**: *arma virumque cano.*

The tokens *arma*, *virum* and *cano* are all classified as `lexical`. (*que* is `enclitic` and the period `.` is `punctuation`) .






##  Implied tokens


::: {.callout-note}
This discussion focuses on adding implied tokens to the tokens table. For more on how elided forms of *sum* and understood repeated verb forms are documented in the list of verbal expressions, see the discussion of 
[verbal units](./verbalunits.qmd).  For further discussion of how implied tokens are related to other tokens in the tokens graph, see the discussion of `arsgrammatica`'s  [graph of syntactic relations](./syntactic-analysis.qmd).
:::


There are three circumstances where `arsgrammatica` inserts implied tokens into its syntax graph. All implied tokens have `None` for their text value.



### Elided forms of `sum`

The verb `sum` ("to be") is often elided in the present tense. A new token with unique ID must be added to the token table, and an entry added to the list of verbal expressions. 

**Example**: *omnia praeclara rara.* 

This is a complete sentence, with a subject phrase *omnia praeclara* and a predicate *rara*. We record the implied form of "to be" with a new token entry with text value `None`, and enter its ID into the list of verbal expressions. 

A particularly important category of elided forms of *sum* is the participle: since there is no present participle of *sum*, its presence is *always* implied only. 


**Example**: *P. Valerius anno post Agrippa Menenio P. Postumio consulibus moritur.*

The phrase *Agrippa Menenio P. Postumio consulibus* is an ablative absolute construction implying a circumstantial participle of "to be".  We will need to create a new token with text value `None`, add an entry with its id in the verbal expressions table, and in the syntax graph treat it as a participle agreeing with each of the two consuls' names.

Elision of *sum* can also occur with multiword compounds such as the perfect passive system. 
   
**Example**: *inde P. Valerius iterum T. Lucretius consules facti.* 

This sentence has a single verbal expression with a perfect passive verb, *facti* with *sunt* omitted. We add a token with text value `None` to the table of tokens. In the syntax graph, it will be related to *facti* as `auxiliary`; there is no need to add an entry to the list of verbal units, since the participle (as the main verb of the compound) will already figure there.




### Understood repeated verb


When parallel verbal constructions repeat the same verbal idea, the verb can be understood rather than repeated in each expression. We must add a new token with unique ID to the token table, and an entry added to the list of verbal expressions. 


**Example**: *sic eius adventus celebrabantur ut famam ingeni exspectatio hominis, exspectationem ipsius adventus admiratioque superaret.*


Here, the conjunction *ut* introduces a parallel result clauses. The first has subject *exspectatio* and direct object *famam*; the second has subjects *adventus* and  *admiratio* and direct object *exspectationem*. The explict verb *superaret* for the first result clause (with singular subject) implies that we would repeat a (plural) form of *supero* for the second result clause.

Understood repetition of a verb is quite common in long sections of indirect speech, where entire passages may appear without repeating any governing verb of speaking or thinking. 


**Example**:  *nimium Tarquinios regno adsuesse; initium a Prisco factum; regnasse dein Ser. Tullium*. 


Here three verbal expressions are each constructed in indirect statement. 
They imply a verb of speaking governing all three verbal expressions, so we add a new token with unique ID to the list of tokens, and add a verbal expression with its ID to the list of verbal expressions.



### Implied substantive

When a relative pronoun or a participle depends on an implied but unexpressed antecedent, we must add a new token with unique ID to the token table.. 

**Example**: *quem dii amant adolescens moritur.*

The relative pronoun *quem* depends on an unexpressed subject of *moritur*. We add a new token for the antecedent that the syntax graph will use both as the antecedent of *quem* and as an implied subject of *moritur*. 

**Example**: *quasi ad alienos durius loquebatur, interrogans eos: Unde venistis?*


The participle *interrogans* depends on an unexpressed antecedent. We add a new token for it. In the syntax graph this token will be both the antecedent of *interrogans* and the subject of *loquebatur*.

This distinguish this from substantive uses of the participle. When the participle can be construed as a direct substantive function, we take it as a single token that the syntax graph can treat like any other substantive.

**Example**: *sapientī sat est.*

We recognize that the participle *sapienti* here is not a circumstantial participle requiring an entry in the verbal expressions table, but can be taken as a substantive "the wise person." There is no need to add any implied antecedent to the list of tokens.