---
title: Verbal units
---

::: {.callout-note}
In `arsgrammatica` the `VerbalExpression` class is the primary implementation of these ideas.
:::

Although `arsgrammatica` tries to account for *all* syntactic features of a Latin text, its analytical scheme is anchored in the reduced Agent-Action-Target model (AAT): all syntactic features are organized around explicit or implicit verbal ideas, that may optionally include agent/target elements (e.g., for transitive active verbs, subject/direct object elements). These verbal expressions (subject-verb ideas) most frequently correspond to clauses in an English translation. (Of course in Latin the subject may be implicit where that is not possible in English.) 


## Verbal constructions

`arsgrammatica` identifies three possible constructions as verbal expressions: finite verbs, infinitives and participles.

1. *Every finite verb* constitutes a verbal expression. Latin finite verbs include the compound forms of the perfect and pluperfect tenses (composed of a past participle plus a form of *sum*) as well as conjugated verbs forms identifiable by tense-mood-voice-person-number. 
2. *Infinitives* constitute a verbal expression when they are constructed as a verbal expression in indirect speech.
3. *Participles* constitute a verbal expression when they have a *circumstantial* sense rather than purely *attributive* sense. 

`arsgrammatica` classifies verbal expressions according to *syntactic type* and *semantic type*.


## Syntactic type

### `independent`

Also called "main" or "principal" verbs, these are syntactically independent finite verbs: their clause is syntactically coherent by itself.

**Example**: *Quo usque tandem abutere, Catilina, patientia nostra?*

*abutere* is an `independent` verbal expresion.

### `dependent`

Finite verbs introduced by a subordinating word (such as a subordinating conjunction or relative pronoun). They cannot appear without an explicit or implicit governing (superior) clause. 

**Example**: *principes Albanorum in patres, ut ea quoque pars rei publicae cresceret, legit.* 

The verb *legit* is an `independent` verbal expression; *cresceret* is `dependent` (introduced by the subordinating conjunction *ut*).

### `direct quote`

Finite verbs in directly quoted speech. 

**Example**:  *Tuum est' inquit, 'Servi regnum.'*

*inquit* is an `independent` verbal unit, while *est* occurs in directly quoted speech and is classifed as `direct quote`.

### `aside`

A finite verb that interrupts the syntactic flow of the surrounding text. 

**Example**: *equidem — pace dixerim deum — eos nos iam populi Romani beneficio esse spero.*


*spero* is `independent`, the infinitive *esse* is part of an indirect statement (below). *dixerim* is an `aside`, as the entire phrase *pace dixerim deum* interrupts the sentence with a syntactically unconneccted verbal expression.



### `indirect statement`

An infinitive construction in indirect speech.

**Example**: *Collatinus negat verbis opus esse.*

*negat* is `indepedendent`; the infinitive *esse* is `indirect speech`.

Note that as with finite verbs, compound verbs constructed from participles plus "to be" use the participle as the verbal expression. (In [the token graph](./syntactic-analysis.qmd), the form of "to be" will related to it as an `auxiliary`.)

**Example**: *facturum enim se fuisse dixit*.

*dixit* is an independent verbal expression, and *facturum fuisse* is the compound form of the future infinitive. The verbal unit wil be anchored to the token *facturum* as `indirect statement`. In the token graph, *esse* will be related to it as `auxiliary`.


### `circumstantial participle`


Participles in a circumstantial sense rather than purely attributive sense.

**Example**: *Anco regnante Lucumo, vir inpiger ac divitiis potens, Romam commigravit*.

*commigravit* is an `independent` verb. The participle *regnante* (agreeing with *Anco*) is circumsstantial ("while Ancus was reigning...")


**Counter example**: *gloria est consentiens laus bonorum*. 
The verb *est* is `independent` with subject *gloria* and predicate *laus*. Here, the participle *consentiens* has an attributive sense with *laus*, "universal praise". This does *not* constitute a verbal expression. (In  [the syntax graph](./syntactic-analysis.qmd), this will be treated like any other attributive or adjectival expression, and will be related to *laus* as `adjectival`.)

When it is unclear whether to take the relation of a participle as attributive or circumstantial, **prefer the treatment as circumstantial participle**. 

**Example**  *ille moriens, cum sciret sagittas hydrae Lernaeae felle tinctas quantam uim haberent ueneni, sanguinem suum exceptum Deianirae dedit*.

The participle *moriens* agrees with *ille*, and the participle *tinctas* agrees with *sagittas*. Treat both as circumstantial participles definiing a verbal expression.








## Semantic type    

`arsgrammatica` recognizes four semantic types for verbal expressions. 

`linking verb` applies to verbs joining a subject and predicate nominative expression (a substantive or adjectival expression).  `intransitive` is for verbs that cannot take a direct object. `transitive active` and `transitive passive` apply to verbs that, in the active voice,  are capable of construction with a direct object. 

Note that in Latin, `transitive active` expressions can be converted to equivalent `transitive passive` expressions under the A-A-T model (and vice versa) by changing the voice of the verb, and the construction of any explicit agent and target as follows:

|Semantic type | Agent | Action | Target|
| --- | ---  | --- | --- |
| `transitive active` | subject | active voice | direct object |
| `transitive passive` | ablative of agent  | passive voice | subject |

### `linking verb`


The most common verb linking a nominative subject with a nominative predicate is *sum*.

**Example**: *Etruria erat vicina*.


The verb *erat* is a `linking verb` with subject *Etruria* and predicate *vicina*.

### `intransitive`

Active- or passive-voice verbal  expressions that are intransitive in sense (i.e., that cannot take a direct object).

**Example**: *principes Albanorum in patres, ut ea quoque pars rei publicae cresceret, legit*.

The verb *cresceret* is an active-voice form that cannot take a direct object. It is `intransitive`.


### `transitive active`

Any active-voice verbal expression with a transitive sense, so is capable of taking a direct object.

**Example**: *principes Albanorum in patres, ut ea quoque pars rei publicae cresceret, legit*.

The verb *legit* is *transitive active* with an explicit direct object *principes*.

### `transitive passive`

Any passive-voice verbal expression with a transitive sense, so is capable of taking a construction with the ablative of agent. 

*urbs a Romulo condita est*

The compound verb form *condita est* is `transitive passive` with grammatical subject `urbs` and agent expressed by the prepositional phrase `a Romulo`. 




## Handling implied verbal expressions

The discussion of [tokenization](./tokens.qmd) introduced the idea of *implied* verbal expressions. There are two circumstances where we need to create an entry in the list of verbal expressions for an implied verbal expression.


### Omitted forms of *sum*

**Example**: *omnia praeclara rara.* 

This is a complete sentence, with a subject phrase *omnia praeclara* and a predicate *rara*. We record the implied form of "to be" with a new token entry, and enter the token's ID into the list of verbal expressions. Here, the implied token will classified as syntactic type `independent` and semantic thpe `linking verb`.
 
 
 Elision of *sum* can also occur with multiword compounds such as the perfect passive system. This situtation does not require an entry in the verbal units table because the participle itself is a real token that will already be entered there to anchor the verbal expression.

 **Example**:  *inde P. Valerius iterum T. Lucretius consules facti.* 
 
 This complete sentence has a single verbal expression with a perfect passive verb, *facti* with *sunt* omitted. *facti* itself is entered in the list of verbal expressions (syntactic type `independent`, semantic type `transitive passive`). The token graph will still add a new token with unique ID and `None` for its text value to record the elided *sunt*, but this new token will be related to *facti* as its `auxiliary`. 
 
 
 One important category of elided forms of *sum* is the participle: since there is no present participle of *sum*, its presence is *always* implied only. 
 
 **Example**: *P. Valerius anno post Agrippa Menenio P. Postumio consulibus moritur.* 
 
 The phrase *Agrippa Menenio P. Postumio consulibus* is an ablative absolute construction implying a circumstantial participle of "to be". We must add a new token with a unique ID to the token table and use its ID for a new entry in the list of verbal expressions. Its syntactic type will be `circumstantial participle` and its semantic type will be `linking verb` since this participial phrase is a predicate construction ("when Agrippa Menenius and Publius Postumius were consuls...")


### Understood repeated verb


When parallel verbal constructions repeat the same verbal idea, the verb can be understood rather than repeated in each expression. We must add a new token with unique ID to the token table, and an entry added to the list of verbal expressions.

**Example**: *sic eius adventus celebrabantur ut famam ingeni exspectatio hominis, exspectationem ipsius adventus admiratioque superaret.*

Here, the conjunction *ut* introduces two parallel result clauses. The first has subject *exspectatio* and direct object *famam*; the second has subjects *adventus* and *admiratio* and direct object *exspectationem*. The explict verb *superaret* is recorded in the verbal entry table for the first result clause (with singular subject *exspectatio*); this implies that we would repeat a (plural) form of *supero* for the second result clause. We must add an entry to the token table, and an entry with its unique to the verbal expressions list. Like the verbal expression it repeats, it will be of syntactic type `dependent` (after *ut*), and semantic type `transitive active`.


Implied repetition of verbal expressions is particularly common in indirect discourse.Entire passages may appear without repeating any governing verb of speaking or thinking. In this situation, we must add new token with unique ID to the token table, with `None` for its text value, and use its ID for new entry in the list of verbal expressions.

**Example**: *nimium Tarquinios regno adsuesse; initium a Prisco factum; regnasse dein Ser. Tullium*. 
This sentence has three verbal expressions each constructed in indirect statement. They imply a verb of speaking governing all three verbal expressions, so we add a new token with unique ID to the list of tokens, and add a verbal expression with its ID to the list of verbal expressions. Here, we assume that the understood verbal expression is of syntatic type `independent`, with  semantic type `transitive active`. 
