---
title: Recipes
---


Guides for using `arsgrammatica` for particular tasks.

## Analyzing and visualizing syntax


### Analyzing Latin texts

- [Installing `arsgrammatica`](./install.md)
- [Analyzing Latin syntax with a configured language model](./analysis.qmd)
- [Saving and loading analyses](./saving-loading.qmd)

### Visualizing analyses

- [Highlighting text](./texthiliting.qmd) syntactically in HTML
- Visualizing [syntax graphs with Mermaid](./mermaid.qmd)


### Analyzing analyses as graph structures

- Characterizing syntactic analyses with [graph metrics](./graphmetrics.qmd)
- [Building an Agent-Action-Target (AAT) graph](./aat.qmd)

 

## Training a language model

- [Optimizing](./optimizing.qmd)
- [Comparing models](./bakeoff.qmd)
- [A development work flow](./development.qmd)
- [Harvesting gold examples from real analyses](./harvesting.qmd)
- [Test suite](./testing.qmd)
- [Tokenizing text without analysis](./tokenizing.qmd)


## Managing a language model

- [Estimating tokens budget](./budgetingtokens.qmd)
- [Keeping prompt size manageable](./managing_prompt_size.qmd)

